version: "3.5"

services:
  http:
    image: de10nano-http:v1
    container_name: de10nano-http
    ports:
      - "8080:80"
    volumes:
      - "./default-config-files/nginx.config:/etc/nginx/nginx.conf"
  builder:
    build:
      context: .
      target: builder_runner
    image: de10-nano-builder:v1
    container_name: de10nano-builder
    ports:
      - "4400:4000"
    environment:
      - PASSWORD=password
    cap_add:
      - SYS_PTRACE
    volumes:
      - external_code:/home/builder/src_external
volumes:
  external_code:
