version: "3.5"
services:
  builder:
    build:
      context: .
      target: builder_runner
      network: host
    image: de10-nano-builder:v1
    container_name: de10nano-builder
    ports:
      - "4400:4000"
    environment:
      - PASSWORD=password
    cap_add:
      - SYS_PTRACE
    volumes:
      - /dev:/dev
      - .config/.altera.quartus/:/home/builder/.altera.quartus/:rw
      - ./workspace_persistent:/home/builder/external_workspace:rw
    privileged: true