version: "3.5"
services:
  builder:
    build:
      context: .
      target: builder_runner
      network: host
    image: de10-nano-builder:v1
    container_name: de10nano-builder
    ports:
      - "4400:4000"
    environment:
      - PASSWORD=password
      - TZ=America/Bogota
    cap_add:
      - SYS_PTRACE
    volumes:
      - /dev:/dev
      - .config/.altera.quartus/:/home/builder/.altera.quartus/:rw
      - ./workspace_persistent:/home/builder/external_workspace:rw
    privileged: true
  builder-micro-sd:
    build:
      context: .
      target: builder_micro_sd
    image: de10-nano-builder-micro-sd:v1
    container_name: de10nano-builder-micro-sd
    cap_add:
      - SYS_PTRACE
    volumes:
      - /dev:/dev
      - ./workspace_persistent:/output:rw
    privileged: true
  # builder-eds:
  #   build:
  #     context: eds-tools
  #   image: de10-nano-builder-eds:v1
  #   container_name: de10nano-builder-eds
  #   volumes:
  #     - ./workspace_persistent:/workspace_persistent:rw
  #   privileged: true