version: '3.5'

services:
  downloader:
    build: 
        context: .
        target: downloader
    image: de10nano-downloader:v1
    container_name: de10nano-downloader
    ports:
      - "8080:80"
    volumes:
      - "./default-config-files/nginx.config:/etc/nginx/nginx.conf"
  builder:
    build: 
        context: .
        target: builder
    image: de10-nano-builder:v1
    container_name: de10nano-builder
    ports:
      - "4400:4000"
    environment: 
      - PASSWORD=password
    cap_add:
      - SYS_PTRACE
    stdin_open: true # docker run -i
    tty: true        # docker run -t